# Site settings
baseurl = "http://example.org/"
languageCode = "en-us"
title = "Origin"
theme = "hugrid2"

googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    title = "Origin"
    subtitle = "A crossroad for informational news."
    author = "gndpwnd"
    description = "Hugrid - grid theme for Hugo with an expanding image preview."
    keywords = "Hugo, Hugo theme, grid theme, portfolio, bookmarks, collection, contacts"

    # Body background color
    bodybgcolor = "#000000"

    # Preview container button text
    buttontext = "Go To Site"

    # Footer text
    footertext = "Made with [Hugo](http://gohugo.io). Credits: [gndpwnd](https://github.com/gndpwnd), [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/), [AeroHub](https://github.com/aerohub)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
